using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using FontAwesome.Sharp;
using Guna.UI2.WinForms;

namespace Presentation.Models;

partial class FrmThemNhaCungCap
{
	private IContainer components = null;

	private Guna2BorderlessForm guna2BorderlessForm1;

	private Guna2ShadowForm guna2ShadowForm1;

	private Guna2DragControl guna2DragControl1;

	private Guna2Panel pnlTitleBar;

	private IconPictureBox iconTitle;

	private Label labelTitle;

	private Label labelSubTitle;

	private Guna2ControlBox btnCloseBox;

	private Guna2Panel pnlThongTinCoBan;

	private Label lblTitleThongTinCoBan;

	private Label lblMaNcc;

	private Guna2TextBox txtMaNcc;

	private Label lblAutoCode;

	private Label lblTenNcc;

	private Guna2TextBox txtTenNcc;

	private Label lblNguoiDaiDien;

	private Guna2TextBox txtNguoiDaiDien;

	private Label lblSoDienThoai;

	private Guna2TextBox txtSoDienThoai;

	private IconPictureBox iconPhone;

	private Label lblEmail;

	private Guna2TextBox txtEmail;

	private IconPictureBox iconEmail;

	private Label lblDiaChi;

	private Guna2TextBox txtDiaChi;

	private IconPictureBox iconPin;

	private Label lblMaSoThue;

	private Guna2TextBox txtMaSoThue;

	private IconPictureBox iconTax;

	private Label lblWebsite;

	private Guna2TextBox txtWebsite;

	private IconPictureBox iconWeb;

	private Label lblLoaiNcc;

	private Guna2ComboBox cboLoaiNcc;

	private Label lblTrangThai;

	private Guna2ComboBox cboTrangThai;

	private Guna2Panel pnlThongTinBoSung;

	private Label lblTitleThongTinBoSung;

	private Label lblLogo;

	private Guna2PictureBox picLogo;

	private Guna2Button btnChonLogo;

	private Label lblDieuKhoanThanhToan;

	private Guna2ComboBox cboDieuKhoanThanhToan;

	private Label lblNgayBatDauHopTac;

	private Guna2DateTimePicker dtpNgayBatDau;

	private Label lblKhuVucCungCap;

	private Guna2ComboBox cboKhuVucCungCap;

	private Label lblNhomSachCungCap;

	private FlowLayoutPanel flpNhomSachTags;

	private Label lblGhiChu;

	private Guna2TextBox txtGhiChu;

	private Label lblDemGhiChu;

	private Label lblTaiLieuDinhKem;

	private Guna2Panel pnlTaiLieuDinhKem;

	private IconPictureBox iconAttachment;

	private Label lblAttachmentText;

	private Guna2Button btnChonFile;

	private Guna2Panel pnlThongTinHopTac;

	private Label lblTitleThongTinHopTac;

	private Label lblHanMucCongNo;

	private Guna2TextBox txtHanMucCongNo;

	private Label lblChietKhauMacDinh;

	private Guna2TextBox txtChietKhauMacDinh;

	private Label lblPhuongThucThanhToan;

	private Guna2ComboBox cboPhuongThucThanhToan;

	private Label lblDanhGiaBanDau;

	private Guna2ComboBox cboDanhGiaBanDau;

	private Guna2Panel pnlInfoBanner;

	private IconPictureBox iconInfoBanner;

	private Label lblInfoBannerText;

	private Guna2Panel pnlTomTat;

	private Label lblTitleTomTat;

	private Guna2Panel cardLoaiNcc;

	private IconPictureBox iconBuildingCard;

	private Label lblTitleCardLoaiNcc;

	private Label lblValueCardLoaiNcc;

	private Guna2Panel cardKhuVuc;

	private IconPictureBox iconPinCard;

	private Label lblTitleCardKhuVuc;

	private Label lblValueCardKhuVuc;

	private Guna2Panel cardTrangThaiNcc;

	private IconPictureBox iconStatusCard;

	private Label lblTitleCardTrangThai;

	private Label lblValueCardTrangThai;

	private Guna2Panel cardCongNo;

	private IconPictureBox iconMoneyCard;

	private Label lblTitleCardCongNo;

	private Label lblValueCardCongNo;

	private Guna2Panel pnlNccGanDay;

	private Label lblTitleNccGanDay;

	private FlowLayoutPanel flpRecentNccList;

	private Guna2Button btnLuuTam;

	private Guna2Button btnLuuNhaCungCap;

	private Guna2Button btnHuy;
	protected override void Dispose(bool disposing)
	{
		if (disposing && components != null)
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	private void InitializeComponent()
	{
		this.components = new System.ComponentModel.Container();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges5 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges6 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges7 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges8 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges9 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges10 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges11 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges12 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges13 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges14 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges15 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges16 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges17 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges18 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges19 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges20 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges21 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges22 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges23 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges24 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges25 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges26 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges27 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges28 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges29 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges30 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges31 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges32 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges33 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges34 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges35 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges36 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges37 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges38 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges39 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges40 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges41 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges42 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges43 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges44 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges45 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges46 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges47 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges48 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges49 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges50 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges51 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges52 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges53 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges54 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges55 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges56 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges57 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges58 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges59 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges60 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges61 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges62 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges63 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges64 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges65 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges66 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges67 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges68 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges69 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges70 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges71 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges72 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges73 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges74 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
		this.guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
		this.guna2ShadowForm1 = new Guna.UI2.WinForms.Guna2ShadowForm(this.components);
		this.guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
		this.pnlTitleBar = new Guna.UI2.WinForms.Guna2Panel();
		this.iconTitle = new FontAwesome.Sharp.IconPictureBox();
		this.labelTitle = new System.Windows.Forms.Label();
		this.labelSubTitle = new System.Windows.Forms.Label();
		this.btnCloseBox = new Guna.UI2.WinForms.Guna2ControlBox();
		this.pnlThongTinCoBan = new Guna.UI2.WinForms.Guna2Panel();
		this.lblTitleThongTinCoBan = new System.Windows.Forms.Label();
		this.lblMaNcc = new System.Windows.Forms.Label();
		this.txtMaNcc = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblAutoCode = new System.Windows.Forms.Label();
		this.lblTenNcc = new System.Windows.Forms.Label();
		this.txtTenNcc = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblNguoiDaiDien = new System.Windows.Forms.Label();
		this.txtNguoiDaiDien = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblSoDienThoai = new System.Windows.Forms.Label();
		this.txtSoDienThoai = new Guna.UI2.WinForms.Guna2TextBox();
		this.iconPhone = new FontAwesome.Sharp.IconPictureBox();
		this.lblEmail = new System.Windows.Forms.Label();
		this.txtEmail = new Guna.UI2.WinForms.Guna2TextBox();
		this.iconEmail = new FontAwesome.Sharp.IconPictureBox();
		this.lblDiaChi = new System.Windows.Forms.Label();
		this.txtDiaChi = new Guna.UI2.WinForms.Guna2TextBox();
		this.iconPin = new FontAwesome.Sharp.IconPictureBox();
		this.lblMaSoThue = new System.Windows.Forms.Label();
		this.txtMaSoThue = new Guna.UI2.WinForms.Guna2TextBox();
		this.iconTax = new FontAwesome.Sharp.IconPictureBox();
		this.lblWebsite = new System.Windows.Forms.Label();
		this.txtWebsite = new Guna.UI2.WinForms.Guna2TextBox();
		this.iconWeb = new FontAwesome.Sharp.IconPictureBox();
		this.lblLoaiNcc = new System.Windows.Forms.Label();
		this.cboLoaiNcc = new Guna.UI2.WinForms.Guna2ComboBox();
		this.lblTrangThai = new System.Windows.Forms.Label();
		this.cboTrangThai = new Guna.UI2.WinForms.Guna2ComboBox();
		this.pnlThongTinBoSung = new Guna.UI2.WinForms.Guna2Panel();
		this.lblTitleThongTinBoSung = new System.Windows.Forms.Label();
		this.lblLogo = new System.Windows.Forms.Label();
		this.picLogo = new Guna.UI2.WinForms.Guna2PictureBox();
		this.btnChonLogo = new Guna.UI2.WinForms.Guna2Button();
		this.lblDieuKhoanThanhToan = new System.Windows.Forms.Label();
		this.cboDieuKhoanThanhToan = new Guna.UI2.WinForms.Guna2ComboBox();
		this.lblNgayBatDauHopTac = new System.Windows.Forms.Label();
		this.dtpNgayBatDau = new Guna.UI2.WinForms.Guna2DateTimePicker();
		this.lblKhuVucCungCap = new System.Windows.Forms.Label();
		this.cboKhuVucCungCap = new Guna.UI2.WinForms.Guna2ComboBox();
		this.lblNhomSachCungCap = new System.Windows.Forms.Label();
		this.flpNhomSachTags = new System.Windows.Forms.FlowLayoutPanel();
		this.lblGhiChu = new System.Windows.Forms.Label();
		this.txtGhiChu = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblDemGhiChu = new System.Windows.Forms.Label();
		this.lblTaiLieuDinhKem = new System.Windows.Forms.Label();
		this.pnlTaiLieuDinhKem = new Guna.UI2.WinForms.Guna2Panel();
		this.iconAttachment = new FontAwesome.Sharp.IconPictureBox();
		this.lblAttachmentText = new System.Windows.Forms.Label();
		this.btnChonFile = new Guna.UI2.WinForms.Guna2Button();
		this.pnlThongTinHopTac = new Guna.UI2.WinForms.Guna2Panel();
		this.lblTitleThongTinHopTac = new System.Windows.Forms.Label();
		this.lblHanMucCongNo = new System.Windows.Forms.Label();
		this.txtHanMucCongNo = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblChietKhauMacDinh = new System.Windows.Forms.Label();
		this.txtChietKhauMacDinh = new Guna.UI2.WinForms.Guna2TextBox();
		this.lblPhuongThucThanhToan = new System.Windows.Forms.Label();
		this.cboPhuongThucThanhToan = new Guna.UI2.WinForms.Guna2ComboBox();
		this.lblDanhGiaBanDau = new System.Windows.Forms.Label();
		this.cboDanhGiaBanDau = new Guna.UI2.WinForms.Guna2ComboBox();
		this.pnlInfoBanner = new Guna.UI2.WinForms.Guna2Panel();
		this.iconInfoBanner = new FontAwesome.Sharp.IconPictureBox();
		this.lblInfoBannerText = new System.Windows.Forms.Label();
		this.pnlTomTat = new Guna.UI2.WinForms.Guna2Panel();
		this.lblTitleTomTat = new System.Windows.Forms.Label();
		this.cardLoaiNcc = new Guna.UI2.WinForms.Guna2Panel();
		this.iconBuildingCard = new FontAwesome.Sharp.IconPictureBox();
		this.lblTitleCardLoaiNcc = new System.Windows.Forms.Label();
		this.lblValueCardLoaiNcc = new System.Windows.Forms.Label();
		this.cardKhuVuc = new Guna.UI2.WinForms.Guna2Panel();
		this.iconPinCard = new FontAwesome.Sharp.IconPictureBox();
		this.lblTitleCardKhuVuc = new System.Windows.Forms.Label();
		this.lblValueCardKhuVuc = new System.Windows.Forms.Label();
		this.cardTrangThaiNcc = new Guna.UI2.WinForms.Guna2Panel();
		this.iconStatusCard = new FontAwesome.Sharp.IconPictureBox();
		this.lblTitleCardTrangThai = new System.Windows.Forms.Label();
		this.lblValueCardTrangThai = new System.Windows.Forms.Label();
		this.cardCongNo = new Guna.UI2.WinForms.Guna2Panel();
		this.iconMoneyCard = new FontAwesome.Sharp.IconPictureBox();
		this.lblTitleCardCongNo = new System.Windows.Forms.Label();
		this.lblValueCardCongNo = new System.Windows.Forms.Label();
		this.pnlNccGanDay = new Guna.UI2.WinForms.Guna2Panel();
		this.lblTitleNccGanDay = new System.Windows.Forms.Label();
		this.flpRecentNccList = new System.Windows.Forms.FlowLayoutPanel();
		this.btnLuuTam = new Guna.UI2.WinForms.Guna2Button();
		this.btnLuuNhaCungCap = new Guna.UI2.WinForms.Guna2Button();
		this.btnHuy = new Guna.UI2.WinForms.Guna2Button();
		this.pnlTitleBar.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconTitle).BeginInit();
		this.pnlThongTinCoBan.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconPhone).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.iconEmail).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.iconPin).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.iconTax).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.iconWeb).BeginInit();
		this.pnlThongTinBoSung.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.picLogo).BeginInit();
		this.pnlTaiLieuDinhKem.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconAttachment).BeginInit();
		this.pnlThongTinHopTac.SuspendLayout();
		this.pnlInfoBanner.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconInfoBanner).BeginInit();
		this.pnlTomTat.SuspendLayout();
		this.cardLoaiNcc.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconBuildingCard).BeginInit();
		this.cardKhuVuc.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconPinCard).BeginInit();
		this.cardTrangThaiNcc.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconStatusCard).BeginInit();
		this.cardCongNo.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)this.iconMoneyCard).BeginInit();
		this.pnlNccGanDay.SuspendLayout();
		base.SuspendLayout();
		this.guna2BorderlessForm1.ContainerControl = this;
		this.guna2BorderlessForm1.DockIndicatorTransparencyValue = 0.6;
		this.guna2BorderlessForm1.TransparentWhileDrag = true;
		this.guna2ShadowForm1.ShadowColor = System.Drawing.Color.FromArgb(80, 90, 120);
		this.guna2ShadowForm1.TargetForm = this;
		this.guna2DragControl1.DockIndicatorTransparencyValue = 0.6;
		this.guna2DragControl1.TargetControl = this.pnlTitleBar;
		this.guna2DragControl1.UseTransparentDrag = true;
		this.pnlTitleBar.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlTitleBar.BorderThickness = 1;
		this.pnlTitleBar.Controls.Add(this.iconTitle);
		this.pnlTitleBar.Controls.Add(this.labelTitle);
		this.pnlTitleBar.Controls.Add(this.labelSubTitle);
		this.pnlTitleBar.Controls.Add(this.btnCloseBox);
		this.pnlTitleBar.CustomizableEdges = customizableEdges;
		this.pnlTitleBar.Dock = System.Windows.Forms.DockStyle.Top;
		this.pnlTitleBar.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.pnlTitleBar.Location = new System.Drawing.Point(0, 0);
		this.pnlTitleBar.Margin = new System.Windows.Forms.Padding(4);
		this.pnlTitleBar.Name = "pnlTitleBar";
		this.pnlTitleBar.ShadowDecoration.CustomizableEdges = customizableEdges2;
		this.pnlTitleBar.Size = new System.Drawing.Size(1750, 81);
		this.pnlTitleBar.TabIndex = 0;
		this.iconTitle.BackColor = System.Drawing.Color.Transparent;
		this.iconTitle.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconTitle.IconChar = FontAwesome.Sharp.IconChar.Store;
		this.iconTitle.IconColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconTitle.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconTitle.IconSize = 35;
		this.iconTitle.Location = new System.Drawing.Point(22, 22);
		this.iconTitle.Margin = new System.Windows.Forms.Padding(4);
		this.iconTitle.Name = "iconTitle";
		this.iconTitle.Size = new System.Drawing.Size(35, 35);
		this.iconTitle.TabIndex = 0;
		this.iconTitle.TabStop = false;
		this.labelTitle.AutoSize = true;
		this.labelTitle.BackColor = System.Drawing.Color.Transparent;
		this.labelTitle.Font = new System.Drawing.Font("Segoe UI", 13.5f, System.Drawing.FontStyle.Bold);
		this.labelTitle.ForeColor = System.Drawing.Color.FromArgb(25, 50, 110);
		this.labelTitle.Location = new System.Drawing.Point(68, 12);
		this.labelTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.labelTitle.Name = "labelTitle";
		this.labelTitle.Size = new System.Drawing.Size(369, 37);
		this.labelTitle.TabIndex = 1;
		this.labelTitle.Text = "THÊM NHÀ CUNG CẤP MỚI";
		this.labelSubTitle.AutoSize = true;
		this.labelSubTitle.BackColor = System.Drawing.Color.Transparent;
		this.labelSubTitle.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.labelSubTitle.ForeColor = System.Drawing.Color.FromArgb(100, 110, 130);
		this.labelSubTitle.Location = new System.Drawing.Point(69, 48);
		this.labelSubTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.labelSubTitle.Name = "labelSubTitle";
		this.labelSubTitle.Size = new System.Drawing.Size(667, 25);
		this.labelSubTitle.TabIndex = 2;
		this.labelSubTitle.Text = "Nhập thông tin liên hệ, logo, điều khoản thanh toán và thiết lập chính thức hợp tác";
		this.btnCloseBox.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
		this.btnCloseBox.BackColor = System.Drawing.Color.Transparent;
		this.btnCloseBox.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnCloseBox.CustomizableEdges = customizableEdges3;
		this.btnCloseBox.FillColor = System.Drawing.Color.Transparent;
		this.btnCloseBox.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.btnCloseBox.Location = new System.Drawing.Point(1681, 18);
		this.btnCloseBox.Margin = new System.Windows.Forms.Padding(4);
		this.btnCloseBox.Name = "btnCloseBox";
		this.btnCloseBox.ShadowDecoration.CustomizableEdges = customizableEdges4;
		this.btnCloseBox.Size = new System.Drawing.Size(52, 45);
		this.btnCloseBox.TabIndex = 3;
		this.pnlThongTinCoBan.BackColor = System.Drawing.Color.White;
		this.pnlThongTinCoBan.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlThongTinCoBan.BorderRadius = 8;
		this.pnlThongTinCoBan.BorderThickness = 1;
		this.pnlThongTinCoBan.Controls.Add(this.lblTitleThongTinCoBan);
		this.pnlThongTinCoBan.Controls.Add(this.lblMaNcc);
		this.pnlThongTinCoBan.Controls.Add(this.txtMaNcc);
		this.pnlThongTinCoBan.Controls.Add(this.lblAutoCode);
		this.pnlThongTinCoBan.Controls.Add(this.lblTenNcc);
		this.pnlThongTinCoBan.Controls.Add(this.txtTenNcc);
		this.pnlThongTinCoBan.Controls.Add(this.lblNguoiDaiDien);
		this.pnlThongTinCoBan.Controls.Add(this.txtNguoiDaiDien);
		this.pnlThongTinCoBan.Controls.Add(this.lblSoDienThoai);
		this.pnlThongTinCoBan.Controls.Add(this.txtSoDienThoai);
		this.pnlThongTinCoBan.Controls.Add(this.iconPhone);
		this.pnlThongTinCoBan.Controls.Add(this.lblEmail);
		this.pnlThongTinCoBan.Controls.Add(this.txtEmail);
		this.pnlThongTinCoBan.Controls.Add(this.iconEmail);
		this.pnlThongTinCoBan.Controls.Add(this.lblDiaChi);
		this.pnlThongTinCoBan.Controls.Add(this.txtDiaChi);
		this.pnlThongTinCoBan.Controls.Add(this.iconPin);
		this.pnlThongTinCoBan.Controls.Add(this.lblMaSoThue);
		this.pnlThongTinCoBan.Controls.Add(this.txtMaSoThue);
		this.pnlThongTinCoBan.Controls.Add(this.iconTax);
		this.pnlThongTinCoBan.Controls.Add(this.lblWebsite);
		this.pnlThongTinCoBan.Controls.Add(this.txtWebsite);
		this.pnlThongTinCoBan.Controls.Add(this.iconWeb);
		this.pnlThongTinCoBan.Controls.Add(this.lblLoaiNcc);
		this.pnlThongTinCoBan.Controls.Add(this.cboLoaiNcc);
		this.pnlThongTinCoBan.Controls.Add(this.lblTrangThai);
		this.pnlThongTinCoBan.Controls.Add(this.cboTrangThai);
		this.pnlThongTinCoBan.CustomizableEdges = customizableEdges5;
		this.pnlThongTinCoBan.FillColor = System.Drawing.Color.White;
		this.pnlThongTinCoBan.Location = new System.Drawing.Point(19, 100);
		this.pnlThongTinCoBan.Margin = new System.Windows.Forms.Padding(4);
		this.pnlThongTinCoBan.Name = "pnlThongTinCoBan";
		this.pnlThongTinCoBan.ShadowDecoration.CustomizableEdges = customizableEdges6;
		this.pnlThongTinCoBan.Size = new System.Drawing.Size(669, 675);
		this.pnlThongTinCoBan.TabIndex = 1;
		this.lblTitleThongTinCoBan.AutoSize = true;
		this.lblTitleThongTinCoBan.BackColor = System.Drawing.Color.White;
		this.lblTitleThongTinCoBan.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
		this.lblTitleThongTinCoBan.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblTitleThongTinCoBan.Location = new System.Drawing.Point(20, 12);
		this.lblTitleThongTinCoBan.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleThongTinCoBan.Name = "lblTitleThongTinCoBan";
		this.lblTitleThongTinCoBan.Size = new System.Drawing.Size(225, 30);
		this.lblTitleThongTinCoBan.TabIndex = 0;
		this.lblTitleThongTinCoBan.Text = "THÔNG TIN CƠ BẢN";
		this.lblMaNcc.AutoSize = true;
		this.lblMaNcc.BackColor = System.Drawing.Color.White;
		this.lblMaNcc.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblMaNcc.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblMaNcc.Location = new System.Drawing.Point(20, 60);
		this.lblMaNcc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblMaNcc.Name = "lblMaNcc";
		this.lblMaNcc.Size = new System.Drawing.Size(155, 23);
		this.lblMaNcc.TabIndex = 1;
		this.lblMaNcc.Text = "Mã nhà cung cấp *";
		this.txtMaNcc.BorderRadius = 6;
		this.txtMaNcc.CustomizableEdges = customizableEdges7;
		this.txtMaNcc.DefaultText = "NCC00128";
		this.txtMaNcc.Font = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Bold);
		this.txtMaNcc.Location = new System.Drawing.Point(188, 52);
		this.txtMaNcc.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtMaNcc.Name = "txtMaNcc";
		this.txtMaNcc.PlaceholderText = "";
		this.txtMaNcc.ReadOnly = true;
		this.txtMaNcc.SelectedText = "";
		this.txtMaNcc.ShadowDecoration.CustomizableEdges = customizableEdges8;
		this.txtMaNcc.Size = new System.Drawing.Size(319, 42);
		this.txtMaNcc.TabIndex = 2;
		this.lblAutoCode.AutoSize = true;
		this.lblAutoCode.BackColor = System.Drawing.Color.White;
		this.lblAutoCode.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblAutoCode.ForeColor = System.Drawing.Color.Gray;
		this.lblAutoCode.Location = new System.Drawing.Point(519, 60);
		this.lblAutoCode.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblAutoCode.Name = "lblAutoCode";
		this.lblAutoCode.Size = new System.Drawing.Size(102, 23);
		this.lblAutoCode.TabIndex = 3;
		this.lblAutoCode.Text = "\ud83d\udd12 Tự động";
		this.lblTenNcc.AutoSize = true;
		this.lblTenNcc.BackColor = System.Drawing.Color.White;
		this.lblTenNcc.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTenNcc.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblTenNcc.Location = new System.Drawing.Point(20, 110);
		this.lblTenNcc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTenNcc.Name = "lblTenNcc";
		this.lblTenNcc.Size = new System.Drawing.Size(157, 23);
		this.lblTenNcc.TabIndex = 4;
		this.lblTenNcc.Text = "Tên nhà cung cấp *";
		this.txtTenNcc.BorderRadius = 6;
		this.txtTenNcc.CustomizableEdges = customizableEdges9;
		this.txtTenNcc.DefaultText = "";
		this.txtTenNcc.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtTenNcc.Location = new System.Drawing.Point(188, 102);
		this.txtTenNcc.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtTenNcc.Name = "txtTenNcc";
		this.txtTenNcc.PlaceholderText = "Nhập tên nhà cung cấp";
		this.txtTenNcc.SelectedText = "";
		this.txtTenNcc.ShadowDecoration.CustomizableEdges = customizableEdges10;
		this.txtTenNcc.Size = new System.Drawing.Size(450, 42);
		this.txtTenNcc.TabIndex = 5;
		this.lblNguoiDaiDien.AutoSize = true;
		this.lblNguoiDaiDien.BackColor = System.Drawing.Color.White;
		this.lblNguoiDaiDien.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblNguoiDaiDien.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblNguoiDaiDien.Location = new System.Drawing.Point(20, 160);
		this.lblNguoiDaiDien.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblNguoiDaiDien.Name = "lblNguoiDaiDien";
		this.lblNguoiDaiDien.Size = new System.Drawing.Size(203, 23);
		this.lblNguoiDaiDien.TabIndex = 6;
		this.lblNguoiDaiDien.Text = "Người đại diện / liên hệ *";
		this.txtNguoiDaiDien.BorderRadius = 6;
		this.txtNguoiDaiDien.CustomizableEdges = customizableEdges11;
		this.txtNguoiDaiDien.DefaultText = "";
		this.txtNguoiDaiDien.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtNguoiDaiDien.Location = new System.Drawing.Point(188, 152);
		this.txtNguoiDaiDien.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtNguoiDaiDien.Name = "txtNguoiDaiDien";
		this.txtNguoiDaiDien.PlaceholderText = "Nhập họ tên người đại diện";
		this.txtNguoiDaiDien.SelectedText = "";
		this.txtNguoiDaiDien.ShadowDecoration.CustomizableEdges = customizableEdges12;
		this.txtNguoiDaiDien.Size = new System.Drawing.Size(450, 42);
		this.txtNguoiDaiDien.TabIndex = 7;
		this.lblSoDienThoai.AutoSize = true;
		this.lblSoDienThoai.BackColor = System.Drawing.Color.White;
		this.lblSoDienThoai.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblSoDienThoai.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblSoDienThoai.Location = new System.Drawing.Point(20, 210);
		this.lblSoDienThoai.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblSoDienThoai.Name = "lblSoDienThoai";
		this.lblSoDienThoai.Size = new System.Drawing.Size(123, 23);
		this.lblSoDienThoai.TabIndex = 8;
		this.lblSoDienThoai.Text = "Số điện thoại *";
		this.txtSoDienThoai.BorderRadius = 6;
		this.txtSoDienThoai.CustomizableEdges = customizableEdges13;
		this.txtSoDienThoai.DefaultText = "";
		this.txtSoDienThoai.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtSoDienThoai.Location = new System.Drawing.Point(188, 202);
		this.txtSoDienThoai.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtSoDienThoai.Name = "txtSoDienThoai";
		this.txtSoDienThoai.PlaceholderText = "Nhập số điện thoại";
		this.txtSoDienThoai.SelectedText = "";
		this.txtSoDienThoai.ShadowDecoration.CustomizableEdges = customizableEdges14;
		this.txtSoDienThoai.Size = new System.Drawing.Size(394, 42);
		this.txtSoDienThoai.TabIndex = 9;
		this.iconPhone.BackColor = System.Drawing.Color.Transparent;
		this.iconPhone.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconPhone.IconChar = FontAwesome.Sharp.IconChar.Phone;
		this.iconPhone.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconPhone.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconPhone.IconSize = 28;
		this.iconPhone.Location = new System.Drawing.Point(594, 210);
		this.iconPhone.Margin = new System.Windows.Forms.Padding(4);
		this.iconPhone.Name = "iconPhone";
		this.iconPhone.Size = new System.Drawing.Size(28, 28);
		this.iconPhone.TabIndex = 10;
		this.iconPhone.TabStop = false;
		this.lblEmail.AutoSize = true;
		this.lblEmail.BackColor = System.Drawing.Color.White;
		this.lblEmail.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblEmail.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblEmail.Location = new System.Drawing.Point(20, 260);
		this.lblEmail.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblEmail.Name = "lblEmail";
		this.lblEmail.Size = new System.Drawing.Size(51, 23);
		this.lblEmail.TabIndex = 11;
		this.lblEmail.Text = "Email";
		this.txtEmail.BorderRadius = 6;
		this.txtEmail.CustomizableEdges = customizableEdges15;
		this.txtEmail.DefaultText = "";
		this.txtEmail.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtEmail.Location = new System.Drawing.Point(188, 252);
		this.txtEmail.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtEmail.Name = "txtEmail";
		this.txtEmail.PlaceholderText = "Nhập email liên hệ";
		this.txtEmail.SelectedText = "";
		this.txtEmail.ShadowDecoration.CustomizableEdges = customizableEdges16;
		this.txtEmail.Size = new System.Drawing.Size(394, 42);
		this.txtEmail.TabIndex = 12;
		this.iconEmail.BackColor = System.Drawing.Color.Transparent;
		this.iconEmail.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconEmail.IconChar = FontAwesome.Sharp.IconChar.Envelope;
		this.iconEmail.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconEmail.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconEmail.IconSize = 28;
		this.iconEmail.Location = new System.Drawing.Point(594, 260);
		this.iconEmail.Margin = new System.Windows.Forms.Padding(4);
		this.iconEmail.Name = "iconEmail";
		this.iconEmail.Size = new System.Drawing.Size(28, 28);
		this.iconEmail.TabIndex = 13;
		this.iconEmail.TabStop = false;
		this.lblDiaChi.AutoSize = true;
		this.lblDiaChi.BackColor = System.Drawing.Color.White;
		this.lblDiaChi.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblDiaChi.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblDiaChi.Location = new System.Drawing.Point(20, 310);
		this.lblDiaChi.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblDiaChi.Name = "lblDiaChi";
		this.lblDiaChi.Size = new System.Drawing.Size(74, 23);
		this.lblDiaChi.TabIndex = 14;
		this.lblDiaChi.Text = "Địa chỉ *";
		this.txtDiaChi.BorderRadius = 6;
		this.txtDiaChi.CustomizableEdges = customizableEdges17;
		this.txtDiaChi.DefaultText = "";
		this.txtDiaChi.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtDiaChi.Location = new System.Drawing.Point(188, 302);
		this.txtDiaChi.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtDiaChi.Multiline = true;
		this.txtDiaChi.Name = "txtDiaChi";
		this.txtDiaChi.PlaceholderText = "Nhập địa chỉ chi tiết";
		this.txtDiaChi.SelectedText = "";
		this.txtDiaChi.ShadowDecoration.CustomizableEdges = customizableEdges18;
		this.txtDiaChi.Size = new System.Drawing.Size(394, 75);
		this.txtDiaChi.TabIndex = 15;
		this.iconPin.BackColor = System.Drawing.Color.Transparent;
		this.iconPin.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconPin.IconChar = FontAwesome.Sharp.IconChar.LocationDot;
		this.iconPin.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconPin.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconPin.IconSize = 28;
		this.iconPin.Location = new System.Drawing.Point(594, 325);
		this.iconPin.Margin = new System.Windows.Forms.Padding(4);
		this.iconPin.Name = "iconPin";
		this.iconPin.Size = new System.Drawing.Size(28, 28);
		this.iconPin.TabIndex = 16;
		this.iconPin.TabStop = false;
		this.lblMaSoThue.AutoSize = true;
		this.lblMaSoThue.BackColor = System.Drawing.Color.White;
		this.lblMaSoThue.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblMaSoThue.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblMaSoThue.Location = new System.Drawing.Point(20, 392);
		this.lblMaSoThue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblMaSoThue.Name = "lblMaSoThue";
		this.lblMaSoThue.Size = new System.Drawing.Size(96, 23);
		this.lblMaSoThue.TabIndex = 17;
		this.lblMaSoThue.Text = "Mã số thuế";
		this.txtMaSoThue.BorderRadius = 6;
		this.txtMaSoThue.CustomizableEdges = customizableEdges19;
		this.txtMaSoThue.DefaultText = "";
		this.txtMaSoThue.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtMaSoThue.Location = new System.Drawing.Point(188, 385);
		this.txtMaSoThue.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtMaSoThue.Name = "txtMaSoThue";
		this.txtMaSoThue.PlaceholderText = "Nhập mã số thuế";
		this.txtMaSoThue.SelectedText = "";
		this.txtMaSoThue.ShadowDecoration.CustomizableEdges = customizableEdges20;
		this.txtMaSoThue.Size = new System.Drawing.Size(394, 42);
		this.txtMaSoThue.TabIndex = 18;
		this.iconTax.BackColor = System.Drawing.Color.Transparent;
		this.iconTax.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconTax.IconChar = FontAwesome.Sharp.IconChar.DriversLicense;
		this.iconTax.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconTax.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconTax.IconSize = 28;
		this.iconTax.Location = new System.Drawing.Point(594, 392);
		this.iconTax.Margin = new System.Windows.Forms.Padding(4);
		this.iconTax.Name = "iconTax";
		this.iconTax.Size = new System.Drawing.Size(28, 28);
		this.iconTax.TabIndex = 19;
		this.iconTax.TabStop = false;
		this.lblWebsite.AutoSize = true;
		this.lblWebsite.BackColor = System.Drawing.Color.White;
		this.lblWebsite.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblWebsite.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblWebsite.Location = new System.Drawing.Point(20, 442);
		this.lblWebsite.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblWebsite.Name = "lblWebsite";
		this.lblWebsite.Size = new System.Drawing.Size(70, 23);
		this.lblWebsite.TabIndex = 20;
		this.lblWebsite.Text = "Website";
		this.txtWebsite.BorderRadius = 6;
		this.txtWebsite.CustomizableEdges = customizableEdges21;
		this.txtWebsite.DefaultText = "";
		this.txtWebsite.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtWebsite.Location = new System.Drawing.Point(188, 435);
		this.txtWebsite.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtWebsite.Name = "txtWebsite";
		this.txtWebsite.PlaceholderText = "Nhập website (nếu có)";
		this.txtWebsite.SelectedText = "";
		this.txtWebsite.ShadowDecoration.CustomizableEdges = customizableEdges22;
		this.txtWebsite.Size = new System.Drawing.Size(394, 42);
		this.txtWebsite.TabIndex = 21;
		this.iconWeb.BackColor = System.Drawing.Color.Transparent;
		this.iconWeb.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconWeb.IconChar = FontAwesome.Sharp.IconChar.Globe;
		this.iconWeb.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconWeb.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconWeb.IconSize = 28;
		this.iconWeb.Location = new System.Drawing.Point(594, 442);
		this.iconWeb.Margin = new System.Windows.Forms.Padding(4);
		this.iconWeb.Name = "iconWeb";
		this.iconWeb.Size = new System.Drawing.Size(28, 28);
		this.iconWeb.TabIndex = 22;
		this.iconWeb.TabStop = false;
		this.lblLoaiNcc.AutoSize = true;
		this.lblLoaiNcc.BackColor = System.Drawing.Color.White;
		this.lblLoaiNcc.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblLoaiNcc.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblLoaiNcc.Location = new System.Drawing.Point(20, 492);
		this.lblLoaiNcc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblLoaiNcc.Name = "lblLoaiNcc";
		this.lblLoaiNcc.Size = new System.Drawing.Size(150, 23);
		this.lblLoaiNcc.TabIndex = 23;
		this.lblLoaiNcc.Text = "Loại nhà cung cấp";
		this.cboLoaiNcc.BackColor = System.Drawing.Color.Transparent;
		this.cboLoaiNcc.BorderRadius = 6;
		this.cboLoaiNcc.CustomizableEdges = customizableEdges23;
		this.cboLoaiNcc.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboLoaiNcc.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboLoaiNcc.FocusedColor = System.Drawing.Color.Empty;
		this.cboLoaiNcc.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboLoaiNcc.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboLoaiNcc.ItemHeight = 28;
		this.cboLoaiNcc.Location = new System.Drawing.Point(188, 485);
		this.cboLoaiNcc.Margin = new System.Windows.Forms.Padding(4);
		this.cboLoaiNcc.Name = "cboLoaiNcc";
		this.cboLoaiNcc.ShadowDecoration.CustomizableEdges = customizableEdges24;
		this.cboLoaiNcc.Size = new System.Drawing.Size(449, 34);
		this.cboLoaiNcc.TabIndex = 24;
		this.lblTrangThai.AutoSize = true;
		this.lblTrangThai.BackColor = System.Drawing.Color.White;
		this.lblTrangThai.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTrangThai.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblTrangThai.Location = new System.Drawing.Point(20, 542);
		this.lblTrangThai.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTrangThai.Name = "lblTrangThai";
		this.lblTrangThai.Size = new System.Drawing.Size(87, 23);
		this.lblTrangThai.TabIndex = 25;
		this.lblTrangThai.Text = "Trạng thái";
		this.cboTrangThai.BackColor = System.Drawing.Color.Transparent;
		this.cboTrangThai.BorderRadius = 6;
		this.cboTrangThai.CustomizableEdges = customizableEdges25;
		this.cboTrangThai.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboTrangThai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboTrangThai.FocusedColor = System.Drawing.Color.Empty;
		this.cboTrangThai.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboTrangThai.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboTrangThai.ItemHeight = 28;
		this.cboTrangThai.Location = new System.Drawing.Point(188, 535);
		this.cboTrangThai.Margin = new System.Windows.Forms.Padding(4);
		this.cboTrangThai.Name = "cboTrangThai";
		this.cboTrangThai.ShadowDecoration.CustomizableEdges = customizableEdges26;
		this.cboTrangThai.Size = new System.Drawing.Size(449, 34);
		this.cboTrangThai.TabIndex = 26;
		this.pnlThongTinBoSung.BackColor = System.Drawing.Color.White;
		this.pnlThongTinBoSung.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlThongTinBoSung.BorderRadius = 8;
		this.pnlThongTinBoSung.BorderThickness = 1;
		this.pnlThongTinBoSung.Controls.Add(this.lblTitleThongTinBoSung);
		this.pnlThongTinBoSung.Controls.Add(this.lblLogo);
		this.pnlThongTinBoSung.Controls.Add(this.picLogo);
		this.pnlThongTinBoSung.Controls.Add(this.btnChonLogo);
		this.pnlThongTinBoSung.Controls.Add(this.lblDieuKhoanThanhToan);
		this.pnlThongTinBoSung.Controls.Add(this.cboDieuKhoanThanhToan);
		this.pnlThongTinBoSung.Controls.Add(this.lblNgayBatDauHopTac);
		this.pnlThongTinBoSung.Controls.Add(this.dtpNgayBatDau);
		this.pnlThongTinBoSung.Controls.Add(this.lblKhuVucCungCap);
		this.pnlThongTinBoSung.Controls.Add(this.cboKhuVucCungCap);
		this.pnlThongTinBoSung.Controls.Add(this.lblNhomSachCungCap);
		this.pnlThongTinBoSung.Controls.Add(this.flpNhomSachTags);
		this.pnlThongTinBoSung.Controls.Add(this.lblGhiChu);
		this.pnlThongTinBoSung.Controls.Add(this.txtGhiChu);
		this.pnlThongTinBoSung.Controls.Add(this.lblDemGhiChu);
		this.pnlThongTinBoSung.Controls.Add(this.lblTaiLieuDinhKem);
		this.pnlThongTinBoSung.Controls.Add(this.pnlTaiLieuDinhKem);
		this.pnlThongTinBoSung.CustomizableEdges = customizableEdges27;
		this.pnlThongTinBoSung.FillColor = System.Drawing.Color.White;
		this.pnlThongTinBoSung.Location = new System.Drawing.Point(706, 100);
		this.pnlThongTinBoSung.Margin = new System.Windows.Forms.Padding(4);
		this.pnlThongTinBoSung.Name = "pnlThongTinBoSung";
		this.pnlThongTinBoSung.ShadowDecoration.CustomizableEdges = customizableEdges28;
		this.pnlThongTinBoSung.Size = new System.Drawing.Size(594, 675);
		this.pnlThongTinBoSung.TabIndex = 2;
		this.lblTitleThongTinBoSung.AutoSize = true;
		this.lblTitleThongTinBoSung.BackColor = System.Drawing.Color.White;
		this.lblTitleThongTinBoSung.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
		this.lblTitleThongTinBoSung.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblTitleThongTinBoSung.Location = new System.Drawing.Point(20, 12);
		this.lblTitleThongTinBoSung.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleThongTinBoSung.Name = "lblTitleThongTinBoSung";
		this.lblTitleThongTinBoSung.Size = new System.Drawing.Size(240, 30);
		this.lblTitleThongTinBoSung.TabIndex = 0;
		this.lblTitleThongTinBoSung.Text = "THÔNG TIN BỔ SUNG";
		this.lblLogo.AutoSize = true;
		this.lblLogo.BackColor = System.Drawing.Color.White;
		this.lblLogo.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblLogo.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblLogo.Location = new System.Drawing.Point(4, 52);
		this.lblLogo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblLogo.Name = "lblLogo";
		this.lblLogo.Size = new System.Drawing.Size(167, 23);
		this.lblLogo.TabIndex = 1;
		this.lblLogo.Text = "Logo / Hình đại diện";
		this.picLogo.BackColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.picLogo.BorderRadius = 6;
		this.picLogo.CustomizableEdges = customizableEdges29;
		this.picLogo.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.picLogo.ImageRotate = 0f;
		this.picLogo.Location = new System.Drawing.Point(175, 52);
		this.picLogo.Margin = new System.Windows.Forms.Padding(4);
		this.picLogo.Name = "picLogo";
		this.picLogo.ShadowDecoration.CustomizableEdges = customizableEdges30;
		this.picLogo.Size = new System.Drawing.Size(244, 144);
		this.picLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
		this.picLogo.TabIndex = 2;
		this.picLogo.TabStop = false;
		this.btnChonLogo.BorderColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.btnChonLogo.BorderRadius = 6;
		this.btnChonLogo.BorderThickness = 1;
		this.btnChonLogo.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnChonLogo.CustomizableEdges = customizableEdges31;
		this.btnChonLogo.FillColor = System.Drawing.Color.FromArgb(240, 246, 255);
		this.btnChonLogo.Font = new System.Drawing.Font("Segoe UI", 8.5f, System.Drawing.FontStyle.Bold);
		this.btnChonLogo.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.btnChonLogo.Location = new System.Drawing.Point(431, 94);
		this.btnChonLogo.Margin = new System.Windows.Forms.Padding(4);
		this.btnChonLogo.Name = "btnChonLogo";
		this.btnChonLogo.ShadowDecoration.CustomizableEdges = customizableEdges32;
		this.btnChonLogo.Size = new System.Drawing.Size(138, 45);
		this.btnChonLogo.TabIndex = 3;
		this.btnChonLogo.Text = "\ud83d\udce4 Chọn ảnh";
		this.lblDieuKhoanThanhToan.AutoSize = true;
		this.lblDieuKhoanThanhToan.BackColor = System.Drawing.Color.White;
		this.lblDieuKhoanThanhToan.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblDieuKhoanThanhToan.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblDieuKhoanThanhToan.Location = new System.Drawing.Point(4, 204);
		this.lblDieuKhoanThanhToan.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblDieuKhoanThanhToan.Name = "lblDieuKhoanThanhToan";
		this.lblDieuKhoanThanhToan.Size = new System.Drawing.Size(187, 23);
		this.lblDieuKhoanThanhToan.TabIndex = 4;
		this.lblDieuKhoanThanhToan.Text = "Điều khoản thanh toán";
		this.cboDieuKhoanThanhToan.BackColor = System.Drawing.Color.Transparent;
		this.cboDieuKhoanThanhToan.BorderRadius = 6;
		this.cboDieuKhoanThanhToan.CustomizableEdges = customizableEdges33;
		this.cboDieuKhoanThanhToan.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboDieuKhoanThanhToan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboDieuKhoanThanhToan.FocusedColor = System.Drawing.Color.Empty;
		this.cboDieuKhoanThanhToan.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboDieuKhoanThanhToan.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboDieuKhoanThanhToan.ItemHeight = 28;
		this.cboDieuKhoanThanhToan.Location = new System.Drawing.Point(17, 231);
		this.cboDieuKhoanThanhToan.Margin = new System.Windows.Forms.Padding(4);
		this.cboDieuKhoanThanhToan.Name = "cboDieuKhoanThanhToan";
		this.cboDieuKhoanThanhToan.ShadowDecoration.CustomizableEdges = customizableEdges34;
		this.cboDieuKhoanThanhToan.Size = new System.Drawing.Size(549, 34);
		this.cboDieuKhoanThanhToan.TabIndex = 5;
		this.lblNgayBatDauHopTac.AutoSize = true;
		this.lblNgayBatDauHopTac.BackColor = System.Drawing.Color.White;
		this.lblNgayBatDauHopTac.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblNgayBatDauHopTac.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblNgayBatDauHopTac.Location = new System.Drawing.Point(4, 271);
		this.lblNgayBatDauHopTac.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblNgayBatDauHopTac.Name = "lblNgayBatDauHopTac";
		this.lblNgayBatDauHopTac.Size = new System.Drawing.Size(189, 23);
		this.lblNgayBatDauHopTac.TabIndex = 6;
		this.lblNgayBatDauHopTac.Text = "Ngày bắt đầu hợp tác *";
		this.dtpNgayBatDau.BorderRadius = 6;
		this.dtpNgayBatDau.Checked = true;
		this.dtpNgayBatDau.CustomFormat = "dd/MM/yyyy";
		this.dtpNgayBatDau.CustomizableEdges = customizableEdges35;
		this.dtpNgayBatDau.FillColor = System.Drawing.Color.White;
		this.dtpNgayBatDau.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.dtpNgayBatDau.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
		this.dtpNgayBatDau.Location = new System.Drawing.Point(19, 302);
		this.dtpNgayBatDau.Margin = new System.Windows.Forms.Padding(4);
		this.dtpNgayBatDau.MaxDate = new System.DateTime(9998, 12, 31, 0, 0, 0, 0);
		this.dtpNgayBatDau.MinDate = new System.DateTime(1753, 1, 1, 0, 0, 0, 0);
		this.dtpNgayBatDau.Name = "dtpNgayBatDau";
		this.dtpNgayBatDau.ShadowDecoration.CustomizableEdges = customizableEdges36;
		this.dtpNgayBatDau.Size = new System.Drawing.Size(550, 42);
		this.dtpNgayBatDau.TabIndex = 7;
		this.dtpNgayBatDau.Value = new System.DateTime(2026, 7, 9, 0, 0, 0, 0);
		this.lblKhuVucCungCap.AutoSize = true;
		this.lblKhuVucCungCap.BackColor = System.Drawing.Color.White;
		this.lblKhuVucCungCap.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblKhuVucCungCap.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblKhuVucCungCap.Location = new System.Drawing.Point(4, 350);
		this.lblKhuVucCungCap.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblKhuVucCungCap.Name = "lblKhuVucCungCap";
		this.lblKhuVucCungCap.Size = new System.Drawing.Size(146, 23);
		this.lblKhuVucCungCap.TabIndex = 8;
		this.lblKhuVucCungCap.Text = "Khu vực cung cấp";
		this.cboKhuVucCungCap.BackColor = System.Drawing.Color.Transparent;
		this.cboKhuVucCungCap.BorderRadius = 6;
		this.cboKhuVucCungCap.CustomizableEdges = customizableEdges37;
		this.cboKhuVucCungCap.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboKhuVucCungCap.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboKhuVucCungCap.FocusedColor = System.Drawing.Color.Empty;
		this.cboKhuVucCungCap.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboKhuVucCungCap.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboKhuVucCungCap.ItemHeight = 28;
		this.cboKhuVucCungCap.Location = new System.Drawing.Point(20, 381);
		this.cboKhuVucCungCap.Margin = new System.Windows.Forms.Padding(4);
		this.cboKhuVucCungCap.Name = "cboKhuVucCungCap";
		this.cboKhuVucCungCap.ShadowDecoration.CustomizableEdges = customizableEdges38;
		this.cboKhuVucCungCap.Size = new System.Drawing.Size(549, 34);
		this.cboKhuVucCungCap.TabIndex = 9;
		this.lblNhomSachCungCap.AutoSize = true;
		this.lblNhomSachCungCap.BackColor = System.Drawing.Color.White;
		this.lblNhomSachCungCap.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblNhomSachCungCap.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblNhomSachCungCap.Location = new System.Drawing.Point(4, 429);
		this.lblNhomSachCungCap.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblNhomSachCungCap.Name = "lblNhomSachCungCap";
		this.lblNhomSachCungCap.Size = new System.Drawing.Size(263, 23);
		this.lblNhomSachCungCap.TabIndex = 10;
		this.lblNhomSachCungCap.Text = "Sản phẩm / nhóm sách cung cấp";
		this.flpNhomSachTags.AutoScroll = true;
		this.flpNhomSachTags.BackColor = System.Drawing.Color.White;
		this.flpNhomSachTags.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.flpNhomSachTags.Location = new System.Drawing.Point(20, 456);
		this.flpNhomSachTags.Margin = new System.Windows.Forms.Padding(4);
		this.flpNhomSachTags.Name = "flpNhomSachTags";
		this.flpNhomSachTags.Size = new System.Drawing.Size(550, 44);
		this.flpNhomSachTags.TabIndex = 11;
		this.lblGhiChu.AutoSize = true;
		this.lblGhiChu.BackColor = System.Drawing.Color.White;
		this.lblGhiChu.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblGhiChu.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblGhiChu.Location = new System.Drawing.Point(4, 504);
		this.lblGhiChu.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblGhiChu.Name = "lblGhiChu";
		this.lblGhiChu.Size = new System.Drawing.Size(69, 23);
		this.lblGhiChu.TabIndex = 12;
		this.lblGhiChu.Text = "Ghi chú";
		this.txtGhiChu.BorderRadius = 6;
		this.txtGhiChu.CustomizableEdges = customizableEdges39;
		this.txtGhiChu.DefaultText = "";
		this.txtGhiChu.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.txtGhiChu.Location = new System.Drawing.Point(20, 531);
		this.txtGhiChu.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtGhiChu.Multiline = true;
		this.txtGhiChu.Name = "txtGhiChu";
		this.txtGhiChu.PlaceholderText = "Nhập ghi chú thêm (nếu có)...";
		this.txtGhiChu.SelectedText = "";
		this.txtGhiChu.ShadowDecoration.CustomizableEdges = customizableEdges40;
		this.txtGhiChu.Size = new System.Drawing.Size(550, 75);
		this.txtGhiChu.TabIndex = 13;
		this.lblDemGhiChu.AutoSize = true;
		this.lblDemGhiChu.BackColor = System.Drawing.Color.White;
		this.lblDemGhiChu.Font = new System.Drawing.Font("Segoe UI", 7.5f);
		this.lblDemGhiChu.ForeColor = System.Drawing.Color.Gray;
		this.lblDemGhiChu.Location = new System.Drawing.Point(519, 610);
		this.lblDemGhiChu.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblDemGhiChu.Name = "lblDemGhiChu";
		this.lblDemGhiChu.Size = new System.Drawing.Size(47, 20);
		this.lblDemGhiChu.TabIndex = 14;
		this.lblDemGhiChu.Text = "0/500";
		this.lblTaiLieuDinhKem.AutoSize = true;
		this.lblTaiLieuDinhKem.BackColor = System.Drawing.Color.White;
		this.lblTaiLieuDinhKem.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTaiLieuDinhKem.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblTaiLieuDinhKem.Location = new System.Drawing.Point(4, 615);
		this.lblTaiLieuDinhKem.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTaiLieuDinhKem.Name = "lblTaiLieuDinhKem";
		this.lblTaiLieuDinhKem.Size = new System.Drawing.Size(138, 23);
		this.lblTaiLieuDinhKem.TabIndex = 15;
		this.lblTaiLieuDinhKem.Text = "Tài liệu đính kèm";
		this.pnlTaiLieuDinhKem.BorderColor = System.Drawing.Color.FromArgb(200, 205, 215);
		this.pnlTaiLieuDinhKem.BorderRadius = 6;
		this.pnlTaiLieuDinhKem.BorderThickness = 1;
		this.pnlTaiLieuDinhKem.Controls.Add(this.iconAttachment);
		this.pnlTaiLieuDinhKem.Controls.Add(this.lblAttachmentText);
		this.pnlTaiLieuDinhKem.Controls.Add(this.btnChonFile);
		this.pnlTaiLieuDinhKem.CustomizableEdges = customizableEdges41;
		this.pnlTaiLieuDinhKem.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.pnlTaiLieuDinhKem.Location = new System.Drawing.Point(175, 615);
		this.pnlTaiLieuDinhKem.Margin = new System.Windows.Forms.Padding(4);
		this.pnlTaiLieuDinhKem.Name = "pnlTaiLieuDinhKem";
		this.pnlTaiLieuDinhKem.ShadowDecoration.CustomizableEdges = customizableEdges42;
		this.pnlTaiLieuDinhKem.Size = new System.Drawing.Size(395, 48);
		this.pnlTaiLieuDinhKem.TabIndex = 16;
		this.iconAttachment.BackColor = System.Drawing.Color.Transparent;
		this.iconAttachment.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconAttachment.IconChar = FontAwesome.Sharp.IconChar.Paperclip;
		this.iconAttachment.IconColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.iconAttachment.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconAttachment.IconSize = 22;
		this.iconAttachment.Location = new System.Drawing.Point(12, 12);
		this.iconAttachment.Margin = new System.Windows.Forms.Padding(4);
		this.iconAttachment.Name = "iconAttachment";
		this.iconAttachment.Size = new System.Drawing.Size(22, 22);
		this.iconAttachment.TabIndex = 0;
		this.iconAttachment.TabStop = false;
		this.lblAttachmentText.AutoSize = true;
		this.lblAttachmentText.BackColor = System.Drawing.Color.Transparent;
		this.lblAttachmentText.Font = new System.Drawing.Font("Segoe UI", 8f);
		this.lblAttachmentText.ForeColor = System.Drawing.Color.FromArgb(100, 110, 125);
		this.lblAttachmentText.Location = new System.Drawing.Point(40, 12);
		this.lblAttachmentText.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblAttachmentText.Name = "lblAttachmentText";
		this.lblAttachmentText.Size = new System.Drawing.Size(182, 21);
		this.lblAttachmentText.TabIndex = 1;
		this.lblAttachmentText.Text = "Kéo thả file vào đây hoặc";
		this.btnChonFile.BorderColor = System.Drawing.Color.FromArgb(200, 205, 215);
		this.btnChonFile.BorderRadius = 4;
		this.btnChonFile.BorderThickness = 1;
		this.btnChonFile.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnChonFile.CustomizableEdges = customizableEdges43;
		this.btnChonFile.FillColor = System.Drawing.Color.White;
		this.btnChonFile.Font = new System.Drawing.Font("Segoe UI", 8f, System.Drawing.FontStyle.Bold);
		this.btnChonFile.ForeColor = System.Drawing.Color.FromArgb(60, 70, 90);
		this.btnChonFile.Location = new System.Drawing.Point(275, 8);
		this.btnChonFile.Margin = new System.Windows.Forms.Padding(4);
		this.btnChonFile.Name = "btnChonFile";
		this.btnChonFile.ShadowDecoration.CustomizableEdges = customizableEdges44;
		this.btnChonFile.Size = new System.Drawing.Size(110, 32);
		this.btnChonFile.TabIndex = 2;
		this.btnChonFile.Text = "Chọn file";
		this.pnlThongTinHopTac.BackColor = System.Drawing.Color.White;
		this.pnlThongTinHopTac.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlThongTinHopTac.BorderRadius = 8;
		this.pnlThongTinHopTac.BorderThickness = 1;
		this.pnlThongTinHopTac.Controls.Add(this.lblTitleThongTinHopTac);
		this.pnlThongTinHopTac.Controls.Add(this.lblHanMucCongNo);
		this.pnlThongTinHopTac.Controls.Add(this.txtHanMucCongNo);
		this.pnlThongTinHopTac.Controls.Add(this.lblChietKhauMacDinh);
		this.pnlThongTinHopTac.Controls.Add(this.txtChietKhauMacDinh);
		this.pnlThongTinHopTac.Controls.Add(this.lblPhuongThucThanhToan);
		this.pnlThongTinHopTac.Controls.Add(this.cboPhuongThucThanhToan);
		this.pnlThongTinHopTac.Controls.Add(this.lblDanhGiaBanDau);
		this.pnlThongTinHopTac.Controls.Add(this.cboDanhGiaBanDau);
		this.pnlThongTinHopTac.Controls.Add(this.pnlInfoBanner);
		this.pnlThongTinHopTac.CustomizableEdges = customizableEdges45;
		this.pnlThongTinHopTac.FillColor = System.Drawing.Color.White;
		this.pnlThongTinHopTac.Location = new System.Drawing.Point(19, 794);
		this.pnlThongTinHopTac.Margin = new System.Windows.Forms.Padding(4);
		this.pnlThongTinHopTac.Name = "pnlThongTinHopTac";
		this.pnlThongTinHopTac.ShadowDecoration.CustomizableEdges = customizableEdges46;
		this.pnlThongTinHopTac.Size = new System.Drawing.Size(1281, 243);
		this.pnlThongTinHopTac.TabIndex = 3;
		this.lblTitleThongTinHopTac.AutoSize = true;
		this.lblTitleThongTinHopTac.BackColor = System.Drawing.Color.White;
		this.lblTitleThongTinHopTac.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
		this.lblTitleThongTinHopTac.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblTitleThongTinHopTac.Location = new System.Drawing.Point(20, 12);
		this.lblTitleThongTinHopTac.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleThongTinHopTac.Name = "lblTitleThongTinHopTac";
		this.lblTitleThongTinHopTac.Size = new System.Drawing.Size(237, 30);
		this.lblTitleThongTinHopTac.TabIndex = 0;
		this.lblTitleThongTinHopTac.Text = "THÔNG TIN HỢP TÁC";
		this.lblHanMucCongNo.AutoSize = true;
		this.lblHanMucCongNo.BackColor = System.Drawing.Color.White;
		this.lblHanMucCongNo.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblHanMucCongNo.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblHanMucCongNo.Location = new System.Drawing.Point(20, 60);
		this.lblHanMucCongNo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblHanMucCongNo.Name = "lblHanMucCongNo";
		this.lblHanMucCongNo.Size = new System.Drawing.Size(172, 23);
		this.lblHanMucCongNo.TabIndex = 1;
		this.lblHanMucCongNo.Text = "Hạn mức công nợ (đ)";
		this.txtHanMucCongNo.BorderRadius = 6;
		this.txtHanMucCongNo.CustomizableEdges = customizableEdges47;
		this.txtHanMucCongNo.DefaultText = "0 đ";
		this.txtHanMucCongNo.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtHanMucCongNo.Location = new System.Drawing.Point(20, 85);
		this.txtHanMucCongNo.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtHanMucCongNo.Name = "txtHanMucCongNo";
		this.txtHanMucCongNo.PlaceholderText = "";
		this.txtHanMucCongNo.SelectedText = "";
		this.txtHanMucCongNo.ShadowDecoration.CustomizableEdges = customizableEdges48;
		this.txtHanMucCongNo.Size = new System.Drawing.Size(225, 42);
		this.txtHanMucCongNo.TabIndex = 2;
		this.lblChietKhauMacDinh.AutoSize = true;
		this.lblChietKhauMacDinh.BackColor = System.Drawing.Color.White;
		this.lblChietKhauMacDinh.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblChietKhauMacDinh.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblChietKhauMacDinh.Location = new System.Drawing.Point(262, 60);
		this.lblChietKhauMacDinh.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblChietKhauMacDinh.Name = "lblChietKhauMacDinh";
		this.lblChietKhauMacDinh.Size = new System.Drawing.Size(197, 23);
		this.lblChietKhauMacDinh.TabIndex = 3;
		this.lblChietKhauMacDinh.Text = "Chiết khấu mặc định (%)";
		this.txtChietKhauMacDinh.BorderRadius = 6;
		this.txtChietKhauMacDinh.CustomizableEdges = customizableEdges49;
		this.txtChietKhauMacDinh.DefaultText = "0 %";
		this.txtChietKhauMacDinh.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.txtChietKhauMacDinh.Location = new System.Drawing.Point(262, 85);
		this.txtChietKhauMacDinh.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
		this.txtChietKhauMacDinh.Name = "txtChietKhauMacDinh";
		this.txtChietKhauMacDinh.PlaceholderText = "";
		this.txtChietKhauMacDinh.SelectedText = "";
		this.txtChietKhauMacDinh.ShadowDecoration.CustomizableEdges = customizableEdges50;
		this.txtChietKhauMacDinh.Size = new System.Drawing.Size(212, 42);
		this.txtChietKhauMacDinh.TabIndex = 4;
		this.lblPhuongThucThanhToan.AutoSize = true;
		this.lblPhuongThucThanhToan.BackColor = System.Drawing.Color.White;
		this.lblPhuongThucThanhToan.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblPhuongThucThanhToan.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblPhuongThucThanhToan.Location = new System.Drawing.Point(494, 60);
		this.lblPhuongThucThanhToan.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblPhuongThucThanhToan.Name = "lblPhuongThucThanhToan";
		this.lblPhuongThucThanhToan.Size = new System.Drawing.Size(258, 23);
		this.lblPhuongThucThanhToan.TabIndex = 5;
		this.lblPhuongThucThanhToan.Text = "Phương thức thanh toán ưu tiên";
		this.cboPhuongThucThanhToan.BackColor = System.Drawing.Color.Transparent;
		this.cboPhuongThucThanhToan.BorderRadius = 6;
		this.cboPhuongThucThanhToan.CustomizableEdges = customizableEdges51;
		this.cboPhuongThucThanhToan.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboPhuongThucThanhToan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboPhuongThucThanhToan.FocusedColor = System.Drawing.Color.Empty;
		this.cboPhuongThucThanhToan.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboPhuongThucThanhToan.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboPhuongThucThanhToan.ItemHeight = 28;
		this.cboPhuongThucThanhToan.Location = new System.Drawing.Point(494, 85);
		this.cboPhuongThucThanhToan.Margin = new System.Windows.Forms.Padding(4);
		this.cboPhuongThucThanhToan.Name = "cboPhuongThucThanhToan";
		this.cboPhuongThucThanhToan.ShadowDecoration.CustomizableEdges = customizableEdges52;
		this.cboPhuongThucThanhToan.Size = new System.Drawing.Size(249, 34);
		this.cboPhuongThucThanhToan.TabIndex = 6;
		this.lblDanhGiaBanDau.AutoSize = true;
		this.lblDanhGiaBanDau.BackColor = System.Drawing.Color.White;
		this.lblDanhGiaBanDau.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblDanhGiaBanDau.ForeColor = System.Drawing.Color.FromArgb(80, 90, 110);
		this.lblDanhGiaBanDau.Location = new System.Drawing.Point(762, 60);
		this.lblDanhGiaBanDau.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblDanhGiaBanDau.Name = "lblDanhGiaBanDau";
		this.lblDanhGiaBanDau.Size = new System.Drawing.Size(147, 23);
		this.lblDanhGiaBanDau.TabIndex = 7;
		this.lblDanhGiaBanDau.Text = "Đánh giá ban đầu";
		this.cboDanhGiaBanDau.BackColor = System.Drawing.Color.Transparent;
		this.cboDanhGiaBanDau.BorderRadius = 6;
		this.cboDanhGiaBanDau.CustomizableEdges = customizableEdges53;
		this.cboDanhGiaBanDau.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
		this.cboDanhGiaBanDau.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.cboDanhGiaBanDau.FocusedColor = System.Drawing.Color.Empty;
		this.cboDanhGiaBanDau.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.cboDanhGiaBanDau.ForeColor = System.Drawing.Color.FromArgb(68, 88, 112);
		this.cboDanhGiaBanDau.ItemHeight = 28;
		this.cboDanhGiaBanDau.Location = new System.Drawing.Point(762, 85);
		this.cboDanhGiaBanDau.Margin = new System.Windows.Forms.Padding(4);
		this.cboDanhGiaBanDau.Name = "cboDanhGiaBanDau";
		this.cboDanhGiaBanDau.ShadowDecoration.CustomizableEdges = customizableEdges54;
		this.cboDanhGiaBanDau.Size = new System.Drawing.Size(212, 34);
		this.cboDanhGiaBanDau.TabIndex = 8;
		this.pnlInfoBanner.BorderColor = System.Drawing.Color.FromArgb(191, 219, 254);
		this.pnlInfoBanner.BorderRadius = 6;
		this.pnlInfoBanner.BorderThickness = 1;
		this.pnlInfoBanner.Controls.Add(this.iconInfoBanner);
		this.pnlInfoBanner.Controls.Add(this.lblInfoBannerText);
		this.pnlInfoBanner.CustomizableEdges = customizableEdges55;
		this.pnlInfoBanner.FillColor = System.Drawing.Color.FromArgb(239, 246, 255);
		this.pnlInfoBanner.Location = new System.Drawing.Point(20, 162);
		this.pnlInfoBanner.Margin = new System.Windows.Forms.Padding(4);
		this.pnlInfoBanner.Name = "pnlInfoBanner";
		this.pnlInfoBanner.ShadowDecoration.CustomizableEdges = customizableEdges56;
		this.pnlInfoBanner.Size = new System.Drawing.Size(1238, 60);
		this.pnlInfoBanner.TabIndex = 9;
		this.iconInfoBanner.BackColor = System.Drawing.Color.Transparent;
		this.iconInfoBanner.ForeColor = System.Drawing.Color.FromArgb(37, 99, 235);
		this.iconInfoBanner.IconChar = FontAwesome.Sharp.IconChar.CircleInfo;
		this.iconInfoBanner.IconColor = System.Drawing.Color.FromArgb(37, 99, 235);
		this.iconInfoBanner.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconInfoBanner.IconSize = 28;
		this.iconInfoBanner.Location = new System.Drawing.Point(18, 16);
		this.iconInfoBanner.Margin = new System.Windows.Forms.Padding(4);
		this.iconInfoBanner.Name = "iconInfoBanner";
		this.iconInfoBanner.Size = new System.Drawing.Size(28, 28);
		this.iconInfoBanner.TabIndex = 0;
		this.iconInfoBanner.TabStop = false;
		this.lblInfoBannerText.AutoSize = true;
		this.lblInfoBannerText.BackColor = System.Drawing.Color.Transparent;
		this.lblInfoBannerText.Font = new System.Drawing.Font("Segoe UI", 9f);
		this.lblInfoBannerText.ForeColor = System.Drawing.Color.FromArgb(30, 64, 175);
		this.lblInfoBannerText.Location = new System.Drawing.Point(52, 16);
		this.lblInfoBannerText.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblInfoBannerText.Name = "lblInfoBannerText";
		this.lblInfoBannerText.Size = new System.Drawing.Size(589, 25);
		this.lblInfoBannerText.TabIndex = 1;
		this.lblInfoBannerText.Text = "Sau khi lưu, nhà cung cấp sẽ sẵn sàng để lập phiếu nhập trong hệ thống.";
		this.pnlTomTat.BackColor = System.Drawing.Color.White;
		this.pnlTomTat.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlTomTat.BorderRadius = 8;
		this.pnlTomTat.BorderThickness = 1;
		this.pnlTomTat.Controls.Add(this.lblTitleTomTat);
		this.pnlTomTat.Controls.Add(this.cardLoaiNcc);
		this.pnlTomTat.Controls.Add(this.cardKhuVuc);
		this.pnlTomTat.Controls.Add(this.cardTrangThaiNcc);
		this.pnlTomTat.Controls.Add(this.cardCongNo);
		this.pnlTomTat.CustomizableEdges = customizableEdges57;
		this.pnlTomTat.FillColor = System.Drawing.Color.White;
		this.pnlTomTat.Location = new System.Drawing.Point(1319, 100);
		this.pnlTomTat.Margin = new System.Windows.Forms.Padding(4);
		this.pnlTomTat.Name = "pnlTomTat";
		this.pnlTomTat.ShadowDecoration.CustomizableEdges = customizableEdges58;
		this.pnlTomTat.Size = new System.Drawing.Size(412, 338);
		this.pnlTomTat.TabIndex = 4;
		this.lblTitleTomTat.AutoSize = true;
		this.lblTitleTomTat.BackColor = System.Drawing.Color.White;
		this.lblTitleTomTat.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
		this.lblTitleTomTat.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblTitleTomTat.Location = new System.Drawing.Point(20, 12);
		this.lblTitleTomTat.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleTomTat.Name = "lblTitleTomTat";
		this.lblTitleTomTat.Size = new System.Drawing.Size(110, 30);
		this.lblTitleTomTat.TabIndex = 0;
		this.lblTitleTomTat.Text = "TÓM TẮT";
		this.cardLoaiNcc.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.cardLoaiNcc.BorderRadius = 6;
		this.cardLoaiNcc.BorderThickness = 1;
		this.cardLoaiNcc.Controls.Add(this.iconBuildingCard);
		this.cardLoaiNcc.Controls.Add(this.lblTitleCardLoaiNcc);
		this.cardLoaiNcc.Controls.Add(this.lblValueCardLoaiNcc);
		this.cardLoaiNcc.CustomizableEdges = customizableEdges59;
		this.cardLoaiNcc.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.cardLoaiNcc.Location = new System.Drawing.Point(20, 48);
		this.cardLoaiNcc.Margin = new System.Windows.Forms.Padding(4);
		this.cardLoaiNcc.Name = "cardLoaiNcc";
		this.cardLoaiNcc.ShadowDecoration.CustomizableEdges = customizableEdges60;
		this.cardLoaiNcc.Size = new System.Drawing.Size(372, 62);
		this.cardLoaiNcc.TabIndex = 1;
		this.iconBuildingCard.BackColor = System.Drawing.Color.Transparent;
		this.iconBuildingCard.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconBuildingCard.IconChar = FontAwesome.Sharp.IconChar.Store;
		this.iconBuildingCard.IconColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconBuildingCard.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconBuildingCard.IconSize = 28;
		this.iconBuildingCard.Location = new System.Drawing.Point(15, 18);
		this.iconBuildingCard.Margin = new System.Windows.Forms.Padding(4);
		this.iconBuildingCard.Name = "iconBuildingCard";
		this.iconBuildingCard.Size = new System.Drawing.Size(28, 28);
		this.iconBuildingCard.TabIndex = 0;
		this.iconBuildingCard.TabStop = false;
		this.lblTitleCardLoaiNcc.AutoSize = true;
		this.lblTitleCardLoaiNcc.BackColor = System.Drawing.Color.Transparent;
		this.lblTitleCardLoaiNcc.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTitleCardLoaiNcc.ForeColor = System.Drawing.Color.FromArgb(100, 110, 125);
		this.lblTitleCardLoaiNcc.Location = new System.Drawing.Point(56, 10);
		this.lblTitleCardLoaiNcc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleCardLoaiNcc.Name = "lblTitleCardLoaiNcc";
		this.lblTitleCardLoaiNcc.Size = new System.Drawing.Size(81, 23);
		this.lblTitleCardLoaiNcc.TabIndex = 1;
		this.lblTitleCardLoaiNcc.Text = "Loại NCC";
		this.lblValueCardLoaiNcc.AutoSize = true;
		this.lblValueCardLoaiNcc.BackColor = System.Drawing.Color.Transparent;
		this.lblValueCardLoaiNcc.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.lblValueCardLoaiNcc.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblValueCardLoaiNcc.Location = new System.Drawing.Point(56, 31);
		this.lblValueCardLoaiNcc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblValueCardLoaiNcc.Name = "lblValueCardLoaiNcc";
		this.lblValueCardLoaiNcc.Size = new System.Drawing.Size(198, 25);
		this.lblValueCardLoaiNcc.TabIndex = 2;
		this.lblValueCardLoaiNcc.Text = "Nhà sách / phát hành";
		this.cardKhuVuc.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.cardKhuVuc.BorderRadius = 6;
		this.cardKhuVuc.BorderThickness = 1;
		this.cardKhuVuc.Controls.Add(this.iconPinCard);
		this.cardKhuVuc.Controls.Add(this.lblTitleCardKhuVuc);
		this.cardKhuVuc.Controls.Add(this.lblValueCardKhuVuc);
		this.cardKhuVuc.CustomizableEdges = customizableEdges61;
		this.cardKhuVuc.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.cardKhuVuc.Location = new System.Drawing.Point(20, 118);
		this.cardKhuVuc.Margin = new System.Windows.Forms.Padding(4);
		this.cardKhuVuc.Name = "cardKhuVuc";
		this.cardKhuVuc.ShadowDecoration.CustomizableEdges = customizableEdges62;
		this.cardKhuVuc.Size = new System.Drawing.Size(372, 62);
		this.cardKhuVuc.TabIndex = 2;
		this.iconPinCard.BackColor = System.Drawing.Color.Transparent;
		this.iconPinCard.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconPinCard.IconChar = FontAwesome.Sharp.IconChar.LocationDot;
		this.iconPinCard.IconColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.iconPinCard.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconPinCard.IconSize = 28;
		this.iconPinCard.Location = new System.Drawing.Point(15, 18);
		this.iconPinCard.Margin = new System.Windows.Forms.Padding(4);
		this.iconPinCard.Name = "iconPinCard";
		this.iconPinCard.Size = new System.Drawing.Size(28, 28);
		this.iconPinCard.TabIndex = 0;
		this.iconPinCard.TabStop = false;
		this.lblTitleCardKhuVuc.AutoSize = true;
		this.lblTitleCardKhuVuc.BackColor = System.Drawing.Color.Transparent;
		this.lblTitleCardKhuVuc.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTitleCardKhuVuc.ForeColor = System.Drawing.Color.FromArgb(100, 110, 125);
		this.lblTitleCardKhuVuc.Location = new System.Drawing.Point(56, 10);
		this.lblTitleCardKhuVuc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleCardKhuVuc.Name = "lblTitleCardKhuVuc";
		this.lblTitleCardKhuVuc.Size = new System.Drawing.Size(71, 23);
		this.lblTitleCardKhuVuc.TabIndex = 1;
		this.lblTitleCardKhuVuc.Text = "Khu vực";
		this.lblValueCardKhuVuc.AutoSize = true;
		this.lblValueCardKhuVuc.BackColor = System.Drawing.Color.Transparent;
		this.lblValueCardKhuVuc.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.lblValueCardKhuVuc.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblValueCardKhuVuc.Location = new System.Drawing.Point(56, 31);
		this.lblValueCardKhuVuc.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblValueCardKhuVuc.Name = "lblValueCardKhuVuc";
		this.lblValueCardKhuVuc.Size = new System.Drawing.Size(74, 25);
		this.lblValueCardKhuVuc.TabIndex = 2;
		this.lblValueCardKhuVuc.Text = "Hà Nội";
		this.cardTrangThaiNcc.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.cardTrangThaiNcc.BorderRadius = 6;
		this.cardTrangThaiNcc.BorderThickness = 1;
		this.cardTrangThaiNcc.Controls.Add(this.iconStatusCard);
		this.cardTrangThaiNcc.Controls.Add(this.lblTitleCardTrangThai);
		this.cardTrangThaiNcc.Controls.Add(this.lblValueCardTrangThai);
		this.cardTrangThaiNcc.CustomizableEdges = customizableEdges63;
		this.cardTrangThaiNcc.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.cardTrangThaiNcc.Location = new System.Drawing.Point(20, 188);
		this.cardTrangThaiNcc.Margin = new System.Windows.Forms.Padding(4);
		this.cardTrangThaiNcc.Name = "cardTrangThaiNcc";
		this.cardTrangThaiNcc.ShadowDecoration.CustomizableEdges = customizableEdges64;
		this.cardTrangThaiNcc.Size = new System.Drawing.Size(372, 62);
		this.cardTrangThaiNcc.TabIndex = 3;
		this.iconStatusCard.BackColor = System.Drawing.Color.Transparent;
		this.iconStatusCard.ForeColor = System.Drawing.Color.FromArgb(22, 163, 74);
		this.iconStatusCard.IconChar = FontAwesome.Sharp.IconChar.CheckCircle;
		this.iconStatusCard.IconColor = System.Drawing.Color.FromArgb(22, 163, 74);
		this.iconStatusCard.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconStatusCard.IconSize = 28;
		this.iconStatusCard.Location = new System.Drawing.Point(15, 18);
		this.iconStatusCard.Margin = new System.Windows.Forms.Padding(4);
		this.iconStatusCard.Name = "iconStatusCard";
		this.iconStatusCard.Size = new System.Drawing.Size(28, 28);
		this.iconStatusCard.TabIndex = 0;
		this.iconStatusCard.TabStop = false;
		this.lblTitleCardTrangThai.AutoSize = true;
		this.lblTitleCardTrangThai.BackColor = System.Drawing.Color.Transparent;
		this.lblTitleCardTrangThai.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTitleCardTrangThai.ForeColor = System.Drawing.Color.FromArgb(100, 110, 125);
		this.lblTitleCardTrangThai.Location = new System.Drawing.Point(56, 10);
		this.lblTitleCardTrangThai.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleCardTrangThai.Name = "lblTitleCardTrangThai";
		this.lblTitleCardTrangThai.Size = new System.Drawing.Size(89, 23);
		this.lblTitleCardTrangThai.TabIndex = 1;
		this.lblTitleCardTrangThai.Text = "Tình trạng";
		this.lblValueCardTrangThai.AutoSize = true;
		this.lblValueCardTrangThai.BackColor = System.Drawing.Color.Transparent;
		this.lblValueCardTrangThai.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.lblValueCardTrangThai.ForeColor = System.Drawing.Color.FromArgb(22, 163, 74);
		this.lblValueCardTrangThai.Location = new System.Drawing.Point(56, 31);
		this.lblValueCardTrangThai.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblValueCardTrangThai.Name = "lblValueCardTrangThai";
		this.lblValueCardTrangThai.Size = new System.Drawing.Size(158, 25);
		this.lblValueCardTrangThai.TabIndex = 2;
		this.lblValueCardTrangThai.Text = "Đang hoạt động";
		this.cardCongNo.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.cardCongNo.BorderRadius = 6;
		this.cardCongNo.BorderThickness = 1;
		this.cardCongNo.Controls.Add(this.iconMoneyCard);
		this.cardCongNo.Controls.Add(this.lblTitleCardCongNo);
		this.cardCongNo.Controls.Add(this.lblValueCardCongNo);
		this.cardCongNo.CustomizableEdges = customizableEdges65;
		this.cardCongNo.FillColor = System.Drawing.Color.FromArgb(250, 251, 254);
		this.cardCongNo.Location = new System.Drawing.Point(20, 258);
		this.cardCongNo.Margin = new System.Windows.Forms.Padding(4);
		this.cardCongNo.Name = "cardCongNo";
		this.cardCongNo.ShadowDecoration.CustomizableEdges = customizableEdges66;
		this.cardCongNo.Size = new System.Drawing.Size(372, 62);
		this.cardCongNo.TabIndex = 4;
		this.iconMoneyCard.BackColor = System.Drawing.Color.Transparent;
		this.iconMoneyCard.ForeColor = System.Drawing.Color.FromArgb(217, 119, 6);
		this.iconMoneyCard.IconChar = FontAwesome.Sharp.IconChar.Coins;
		this.iconMoneyCard.IconColor = System.Drawing.Color.FromArgb(217, 119, 6);
		this.iconMoneyCard.IconFont = FontAwesome.Sharp.IconFont.Auto;
		this.iconMoneyCard.IconSize = 28;
		this.iconMoneyCard.Location = new System.Drawing.Point(15, 18);
		this.iconMoneyCard.Margin = new System.Windows.Forms.Padding(4);
		this.iconMoneyCard.Name = "iconMoneyCard";
		this.iconMoneyCard.Size = new System.Drawing.Size(28, 28);
		this.iconMoneyCard.TabIndex = 0;
		this.iconMoneyCard.TabStop = false;
		this.lblTitleCardCongNo.AutoSize = true;
		this.lblTitleCardCongNo.BackColor = System.Drawing.Color.Transparent;
		this.lblTitleCardCongNo.Font = new System.Drawing.Font("Segoe UI", 8.5f);
		this.lblTitleCardCongNo.ForeColor = System.Drawing.Color.FromArgb(100, 110, 125);
		this.lblTitleCardCongNo.Location = new System.Drawing.Point(56, 10);
		this.lblTitleCardCongNo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleCardCongNo.Name = "lblTitleCardCongNo";
		this.lblTitleCardCongNo.Size = new System.Drawing.Size(138, 23);
		this.lblTitleCardCongNo.TabIndex = 1;
		this.lblTitleCardCongNo.Text = "Công nợ hiện tại";
		this.lblValueCardCongNo.AutoSize = true;
		this.lblValueCardCongNo.BackColor = System.Drawing.Color.Transparent;
		this.lblValueCardCongNo.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.lblValueCardCongNo.ForeColor = System.Drawing.Color.FromArgb(217, 119, 6);
		this.lblValueCardCongNo.Location = new System.Drawing.Point(56, 31);
		this.lblValueCardCongNo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblValueCardCongNo.Name = "lblValueCardCongNo";
		this.lblValueCardCongNo.Size = new System.Drawing.Size(40, 25);
		this.lblValueCardCongNo.TabIndex = 2;
		this.lblValueCardCongNo.Text = "0 đ";
		this.pnlNccGanDay.BackColor = System.Drawing.Color.White;
		this.pnlNccGanDay.BorderColor = System.Drawing.Color.FromArgb(226, 230, 239);
		this.pnlNccGanDay.BorderRadius = 8;
		this.pnlNccGanDay.BorderThickness = 1;
		this.pnlNccGanDay.Controls.Add(this.lblTitleNccGanDay);
		this.pnlNccGanDay.Controls.Add(this.flpRecentNccList);
		this.pnlNccGanDay.CustomizableEdges = customizableEdges67;
		this.pnlNccGanDay.FillColor = System.Drawing.Color.White;
		this.pnlNccGanDay.Location = new System.Drawing.Point(1319, 450);
		this.pnlNccGanDay.Margin = new System.Windows.Forms.Padding(4);
		this.pnlNccGanDay.Name = "pnlNccGanDay";
		this.pnlNccGanDay.ShadowDecoration.CustomizableEdges = customizableEdges68;
		this.pnlNccGanDay.Size = new System.Drawing.Size(412, 586);
		this.pnlNccGanDay.TabIndex = 5;
		this.lblTitleNccGanDay.AutoSize = true;
		this.lblTitleNccGanDay.BackColor = System.Drawing.Color.White;
		this.lblTitleNccGanDay.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
		this.lblTitleNccGanDay.ForeColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.lblTitleNccGanDay.Location = new System.Drawing.Point(20, 12);
		this.lblTitleNccGanDay.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
		this.lblTitleNccGanDay.Name = "lblTitleNccGanDay";
		this.lblTitleNccGanDay.Size = new System.Drawing.Size(282, 30);
		this.lblTitleNccGanDay.TabIndex = 0;
		this.lblTitleNccGanDay.Text = "NHÀ CUNG CẤP GẦN ĐÂY";
		this.flpRecentNccList.AutoScroll = true;
		this.flpRecentNccList.BackColor = System.Drawing.Color.White;
		this.flpRecentNccList.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
		this.flpRecentNccList.Location = new System.Drawing.Point(20, 52);
		this.flpRecentNccList.Margin = new System.Windows.Forms.Padding(4);
		this.flpRecentNccList.Name = "flpRecentNccList";
		this.flpRecentNccList.Size = new System.Drawing.Size(372, 514);
		this.flpRecentNccList.TabIndex = 1;
		this.flpRecentNccList.WrapContents = false;
		this.btnLuuTam.BorderRadius = 12;
		this.btnLuuTam.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnLuuTam.CustomizableEdges = customizableEdges69;
		this.btnLuuTam.FillColor = System.Drawing.Color.FromArgb(0, 82, 204);
		this.btnLuuTam.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.btnLuuTam.ForeColor = System.Drawing.Color.White;
		this.btnLuuTam.HoverState.FillColor = System.Drawing.Color.FromArgb(0, 70, 180);
		this.btnLuuTam.Location = new System.Drawing.Point(1179, 1044);
		this.btnLuuTam.Margin = new System.Windows.Forms.Padding(4);
		this.btnLuuTam.Name = "btnLuuTam";
		this.btnLuuTam.ShadowDecoration.CustomizableEdges = customizableEdges70;
		this.btnLuuTam.Size = new System.Drawing.Size(162, 46);
		this.btnLuuTam.TabIndex = 6;
		this.btnLuuTam.Text = "\ud83d\udcbe  Lưu tạm";
		this.btnLuuNhaCungCap.BorderRadius = 12;
		this.btnLuuNhaCungCap.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnLuuNhaCungCap.CustomizableEdges = customizableEdges71;
		this.btnLuuNhaCungCap.FillColor = System.Drawing.Color.FromArgb(22, 163, 74);
		this.btnLuuNhaCungCap.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.btnLuuNhaCungCap.ForeColor = System.Drawing.Color.White;
		this.btnLuuNhaCungCap.HoverState.FillColor = System.Drawing.Color.FromArgb(20, 140, 65);
		this.btnLuuNhaCungCap.Location = new System.Drawing.Point(1354, 1044);
		this.btnLuuNhaCungCap.Margin = new System.Windows.Forms.Padding(4);
		this.btnLuuNhaCungCap.Name = "btnLuuNhaCungCap";
		this.btnLuuNhaCungCap.ShadowDecoration.CustomizableEdges = customizableEdges72;
		this.btnLuuNhaCungCap.Size = new System.Drawing.Size(250, 46);
		this.btnLuuNhaCungCap.TabIndex = 7;
		this.btnLuuNhaCungCap.Text = "\ud83d\udcbe  Lưu nhà cung cấp";
		this.btnHuy.BorderColor = System.Drawing.Color.FromArgb(200, 205, 215);
		this.btnHuy.BorderRadius = 12;
		this.btnHuy.BorderThickness = 1;
		this.btnHuy.Cursor = System.Windows.Forms.Cursors.Hand;
		this.btnHuy.CustomizableEdges = customizableEdges73;
		this.btnHuy.FillColor = System.Drawing.Color.White;
		this.btnHuy.Font = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);
		this.btnHuy.ForeColor = System.Drawing.Color.FromArgb(60, 70, 90);
		this.btnHuy.HoverState.FillColor = System.Drawing.Color.FromArgb(245, 247, 250);
		this.btnHuy.Location = new System.Drawing.Point(1616, 1044);
		this.btnHuy.Margin = new System.Windows.Forms.Padding(4);
		this.btnHuy.Name = "btnHuy";
		this.btnHuy.ShadowDecoration.CustomizableEdges = customizableEdges74;
		this.btnHuy.Size = new System.Drawing.Size(112, 46);
		this.btnHuy.TabIndex = 8;
		this.btnHuy.Text = "❌  Hủy";
		base.AutoScaleDimensions = new System.Drawing.SizeF(10f, 25f);
		base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
		this.BackColor = System.Drawing.Color.FromArgb(245, 247, 252);
		base.ClientSize = new System.Drawing.Size(1750, 1102);
		base.Controls.Add(this.btnHuy);
		base.Controls.Add(this.btnLuuNhaCungCap);
		base.Controls.Add(this.btnLuuTam);
		base.Controls.Add(this.pnlNccGanDay);
		base.Controls.Add(this.pnlTomTat);
		base.Controls.Add(this.pnlThongTinHopTac);
		base.Controls.Add(this.pnlThongTinBoSung);
		base.Controls.Add(this.pnlThongTinCoBan);
		base.Controls.Add(this.pnlTitleBar);
		base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
		base.Margin = new System.Windows.Forms.Padding(4);
		base.Name = "FrmThemNhaCungCap";
		base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
		this.Text = "Thêm nhà cung cấp mới";
		this.pnlTitleBar.ResumeLayout(false);
		this.pnlTitleBar.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconTitle).EndInit();
		this.pnlThongTinCoBan.ResumeLayout(false);
		this.pnlThongTinCoBan.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconPhone).EndInit();
		((System.ComponentModel.ISupportInitialize)this.iconEmail).EndInit();
		((System.ComponentModel.ISupportInitialize)this.iconPin).EndInit();
		((System.ComponentModel.ISupportInitialize)this.iconTax).EndInit();
		((System.ComponentModel.ISupportInitialize)this.iconWeb).EndInit();
		this.pnlThongTinBoSung.ResumeLayout(false);
		this.pnlThongTinBoSung.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.picLogo).EndInit();
		this.pnlTaiLieuDinhKem.ResumeLayout(false);
		this.pnlTaiLieuDinhKem.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconAttachment).EndInit();
		this.pnlThongTinHopTac.ResumeLayout(false);
		this.pnlThongTinHopTac.PerformLayout();
		this.pnlInfoBanner.ResumeLayout(false);
		this.pnlInfoBanner.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconInfoBanner).EndInit();
		this.pnlTomTat.ResumeLayout(false);
		this.pnlTomTat.PerformLayout();
		this.cardLoaiNcc.ResumeLayout(false);
		this.cardLoaiNcc.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconBuildingCard).EndInit();
		this.cardKhuVuc.ResumeLayout(false);
		this.cardKhuVuc.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconPinCard).EndInit();
		this.cardTrangThaiNcc.ResumeLayout(false);
		this.cardTrangThaiNcc.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconStatusCard).EndInit();
		this.cardCongNo.ResumeLayout(false);
		this.cardCongNo.PerformLayout();
		((System.ComponentModel.ISupportInitialize)this.iconMoneyCard).EndInit();
		this.pnlNccGanDay.ResumeLayout(false);
		this.pnlNccGanDay.PerformLayout();
		base.ResumeLayout(false);
	}
}
